import classNames from 'classnames'
import dayjs from 'dayjs'
import Head from 'next/head'
import React from 'react'
import { useIntl } from 'react-intl'

import RecordForm from '@/components/biz/record-form'
import Calendar from '@/components/calendar'
import Card from '@/components/card'
import { Curve } from '@/components/chart'
import Bar from '@/components/chart/bar'
import useRequest from '@/hooks/useRequest'
import { range } from '@/lib/pythonic'
import services from '@/services'

import styles from './index.module.sass'

Home.useLayout = true

function Home() {
  const currentYearMonth = dayjs().format('YYYY-MM')
  const lastYearMonth = dayjs().subtract(1, 'year').format('YYYY-MM')
  const i18n = useIntl()
  let greet
  switch (Math.floor(dayjs().hour() / 6)) {
    case 1:
      greet = 'pages.home.greet.morning'
      break
    case 2:
      greet = 'pages.home.greet.afternoon'
      break
    default:
      greet = 'pages.home.greet.evening'
      break
  }
  const thisYear = dayjs().year()
  const thisMonth = dayjs().month()
  const { data: expenseTrendData } = useRequest(() =>
    services.statistic.expenseTrend({
      year: thisYear,
      month: thisMonth
    })
  )
  const { data: balanceTrendData } = useRequest(() =>
    services.statistic.balanceTrend({
      year: thisYear,
      month: thisMonth
    })
  )
  const { data: lastYearExpenseData } = useRequest(() =>
    services.statistic.expense({
      year: thisYear,
      month: thisMonth
    })
  )
  const { data: expenseData } = useRequest(() =>
    services.statistic.expense({
      year: thisYear,
      month: thisMonth
    })
  )
  const { data: expenseTimes } = useRequest(() =>
    services.statistic.expenseTimes({
      year: thisYear,
      month: thisMonth
    })
  )
  return (
    <>
      <Head>
        <title>{i18n.formatMessage({ id: 'pages.home.head.title' })}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/*<link rel="icon" href="/public/favicon.ico" />*/}
      </Head>
      <main className={classNames(styles.main)}>
        <div className={styles.mainContent}>
          <div className={styles.title}>
            <Card
              title={i18n.formatMessage({ id: greet })}
              subtitle={i18n.formatMessage({ id: 'pages.home.greet.subtitle' })}
            />
          </div>
          <div className={styles.trend}>
            <Card
              subtitle={i18n.formatMessage({
                id: 'pages.home.trend.expense'
              })}
              className={styles.trendInner}
              elevation={1}
            >
              {expenseTrendData?.success && (
                <Curve
                  xs={expenseTrendData.data.month}
                  ys={expenseTrendData.data.trend}
                  accentLast
                  showXTicks
                  showYTicks
                  showYAxes
                  showXAxes
                ></Curve>
              )}
            </Card>
            <Card
              subtitle={i18n.formatMessage({ id: 'pages.home.trend.balance' })}
              className={styles.trendInner}
              elevation={1}
            >
              {balanceTrendData?.success && (
                <Curve
                  xs={balanceTrendData.data.month}
                  ys={balanceTrendData.data.trend}
                  accentLast
                  showXTicks
                  showYTicks
                  showYAxes
                  showXAxes
                ></Curve>
              )}
            </Card>
          </div>
          <Card className={classNames(styles.booking)} elevation={1} fill>
            <RecordForm locale={i18n.locale}></RecordForm>
          </Card>
          <Card
            title={'本周支出/支出分析'}
            className={classNames(styles.booking, styles.hiddenXs)}
            elevation={1}
            fill
          ></Card>
        </div>
        <div className={classNames(styles.viceContent, styles.hiddenSmAndDown, styles.hiddenOnPortrait)}>
          <div className={styles.spendCompare}>
            <Card subtitle={lastYearMonth} className={styles.spendCompareInner} elevation={1}>
              {lastYearExpenseData?.success && (
                <Bar
                  xs={range(1, lastYearExpenseData.data.expense.length + 1)}
                  ys={lastYearExpenseData.data.expense}
                  gap={2.5}
                  showXTicks
                  showYTicks
                  showYAxes
                  showXAxes
                ></Bar>
              )}
            </Card>
            <Card subtitle={currentYearMonth} className={styles.spendCompareInner} elevation={1}>
              {expenseData?.success && (
                <Bar
                  xs={range(1, expenseData.data.expense.length + 1)}
                  ys={expenseData.data.expense}
                  gap={2.5}
                  showXTicks
                  showYTicks
                  showYAxes
                  showXAxes
                ></Bar>
              )}
            </Card>
          </div>

          <Card className={styles.spendDiff} elevation={1}>
            {expenseTimes?.success && (
              <Calendar
                locale={i18n.locale}
                showToolbar
                hideToolButton
                expense={expenseTimes.data.expenseTimes}
              ></Calendar>
            )}
            {/*{currentDate}消费 <br />*/}
            {/*{lastYear}*/}
          </Card>
          <Card title={'收支统计/账户余额'} className={styles.spendDays} elevation={1}>
            {/*{currentDate}消费 <br />*/}
            {/*{lastYear}*/}
          </Card>
        </div>
      </main>
    </>
  )
}

export default Home
